name: Production deploy Diskont

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    env:
      TARGET_FOLDER: "/var/www/diskont/beta"

    steps:
    - uses: actions/checkout@v1

    - name: GIT pulling from github repository
      uses: appleboy/scp-action@master
      with:
        HOST: ${{ secrets.DISKONT_HOST }}
        USERNAME: ${{ secrets.DISKONT_USERNAME }}
        PORT: ${{ secrets.DISKONT_PORT }}
        KEY: ${{ secrets.DISKONT_SECRET }}
        source: "."
        target: "${{ env.TARGET_FOLDER }}"

    - name: Command using from script
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DISKONT_HOST }}
        USERNAME: ${{ secrets.DISKONT_USERNAME }}
        PORT: ${{ secrets.DISKONT_PORT }}
        KEY: ${{ secrets.DISKONT_SECRET }}
        script_stop: true
        script: |
          git --work-tree="${{ env.TARGET_FOLDER }}" --git-dir="${{ env.TARGET_FOLDER }}/.git" clean -f .
          yarn --cwd "${{ env.TARGET_FOLDER }}"
          yarn --cwd "${{ env.TARGET_FOLDER }}" run build
          pm2 reload beta
          sh /home/devops/deploy.sh "${{ github.event.head_commit.message }}" "Beta.diskont.uz deploy"
